version: '2.4'
services:
  #############################################################
  # Maria DB for CRM system                                   #
  #############################################################
  crm-db:
    hostname: crm-db
    container_name: crm-db
    image: mariadb:10.5.9
    restart: always
    ports:
      - 3308:3306
    volumes:
      - ../db/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    environment:
      TZ: Europe/Berlin
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: crmSys
      MYSQL_USER: crmSys
      MYSQL_PASSWORD: admin
    networks:
      - thesis

networks:
  thesis:
    external: true
